---
os: linux
dist: xenial
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - ANSIBLE=2.9.2
  - ANSIBLE=2.9.3
  - ANSIBLE=2.9.4
  - ANSIBLE=2.9.5
  - ANSIBLE=2.9.6
  - ANSIBLE=2.9.7
  - ANSIBLE=2.9.8
  - ANSIBLE=2.9.9
  - ANSIBLE=2.9.10

services:
- docker

# Install ansible
addons:
  apt:
    packages:
    - python-pip
install:
  # Install ansible
  - pip install ansible==$ANSIBLE
  - pip install molecule[docker,lint]

  # Check ansible version
  - ansible --version
  - molecule --version

script:

  # Run molecule tests
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/