---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
  - name: Look for ECDSA private key
    ansible.builtin.stat:
      path: /etc/ssh/ssh_host_ecdsa_key
    register: ecdsakey
  - name: Ensure ECDSA private key was not regenerated
    ansible.builtin.assert:
      that: not ecdsakey.stat.exists
      success_msg: "ECDSA private key is not present"
  - name: Look for ECDSA public key
    ansible.builtin.stat:
      path: /etc/ssh/ssh_host_ecdsa_key.pub
    register: ecdsa
  - name: Ensure ECDSA public key was not regenerated
    ansible.builtin.assert:
      that: not ecdsa.stat.exists
      success_msg: "ECDSA public key is not present"
