name: Release
'on':
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: 'mwmahlberg.sssh'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    outputs:
      release_url: ${{ steps.release.outputs.html_url }}
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'mwmahlberg.sssh'
      - name: Generate changelog.
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          reverseOrder: true
          restrictToTypes: >
            feat, feature,
            fix, bugfix,
            perf,
            refactor,
            test, tests, chore, ci,
            doc, docs
          excludeScopes: internal, dev
      - name: Create Release
        id: 'release'
        uses: ncipollo/release-action@v1.16.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}       
  galaxy:
    name: Import to Galaxy
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'mwmahlberg.sssh'
      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy.
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)